version: '3.3'

services:
  api:
    build: .
    ports:
      - '6767'
    networks:
      - api.network
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - api.network


networks:
  api.network:
