version: '3.3'

services:
  api:
    build: .
    ports:
      - 6767
    depends_on:
      - db
    networks:
      - private
    restart: always
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - db
    ports:
      - 80:80
    networks:
      - private
    restart: always
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=arely
      - POSTGRES_DB=songs
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432
    networks:
      - private

networks:
  private:

volumes:
  postgres: